import { SignInButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

export default function Home() {
  const user = useUser();
  const router = useRouter();

  useEffect(() => {
    if (user.isLoaded && user.isSignedIn) {
      router
        .push("/home")
        .then(() => {
          // The navigation was successful
        })
        .catch((error) => {
          // Handle any errors that occurred during navigation
          console.error(error);
        });
    }
  }, [user, router]);

  return (
    <>
      <Head>
        <title>T3xercise</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen w-screen justify-center">
        <div className="flex h-full min-h-screen w-full flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] md:max-w-2xl">
          <div className="flex h-full justify-center border-b border-slate-400 p-4">
            {!user.isLoaded || !user.isSignedIn ? (
              <div className=" flex flex-col justify-center text-center text-white">
                <div className="flex h-1/4 flex-col justify-normal">
                  <h1 className="handwrite mb-2 text-6xl tracking-tight sm:text-[5rem]">
                    T3XERCISE
                  </h1>
                  <h1 className="handwrite text-3xl font-extrabold tracking-tight sm:text-[5rem]">
                    Build a{" "}
                    <span className="handwrite text-[hsl(280,100%,70%)]">
                      Workout
                    </span>
                  </h1>
                </div>
                <div className="h-1/4 flex-col justify-normal">
                  <SignInButton>
                    <button className="handwrite rounded-full border border-dashed py-1 px-3 text-5xl border-transparent">
                      sign in
                    </button>
                  </SignInButton>
                </div>
              </div>
            ) : null}
          </div>
        </div>
      </main>
    </>
  );
}
