import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import { ExerciseSkeleton } from "~/components/exercise";
import { api } from "~/utils/api";

export default function Home() {
  const user = useUser();
  const { data, isLoading } = api.exercises.getAll.useQuery();
  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Create some exercises...</div>;

  return (
    <>
      <Head>
        <title>T3xercise</title>ּ
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-red-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {!user.isSignedIn && (
              <div className="flex justify-center">
                <p>hello</p>
                <SignInButton />
              </div>
            )}
            {user.isSignedIn && <CreateExerciseWizard />}
          </div>
          <div className="flex flex-col">
            {[...data]?.map((exercise) => (
              <div className="border-b border-slate-400 p-8" key={exercise.id}>
               <ExerciseSkeleton exercise={exercise}/>
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}

const CreateExerciseWizard = () => {
  const { user } = useUser();

  if (!user) return null;

  return (
    <div className="flex w-full gap-3">
      <img
        src={user.imageUrl}
        alt="Profile Image"
        className="h-14 w-14 rounded-full"
      />
      <input className="bg-transparent w-full" placeholder="type here" />
    </div>
  );
};
