import { useUser } from "@clerk/nextjs";
import Head from "next/head";
import { api } from "~/utils/api";

export default function Home() {
  const user = useUser();
  const { data } = api.exercises.getAll.useQuery();
  return (
    <>
      <Head>
        <title>T3xercise</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Build a <span className="text-[hsl(280,100%,70%)]">Workout</span>
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8"></div>
          <p className="text-2xl text-white">
            {data ? `hello ${user.user?.firstName?.toLowerCase()} lets see your exercises!` : "Loading tRPC query..."}
          </p>
          <div>
            {data?.map((exercise)=> (<div key={exercise.id}>{exercise.Title}</div>))}
          </div>
        </div>
      </main>
    </>
  );
}
